### ISSUE TITLE
Les images ne devraient pas être dans le dossier `_static`

### ISSUE THREAD

**Issue by n-peugnet** [club-1/docs#122]
J'avais mal compris le fonctionnement de Sphinx par rapport aux images. En fait il est inutile de les mettre dans le dossier `_static`. Il créé lui-même un dossier `_images` dans le site final pour y ranger les images. C'est même un problème car toutes les images sont de fait dupliquées, une fois dans le dossier `_images` et une autre dans le dossier `_static`.

Du coup il faudrait choisir une nouvelle organisation des images. Je pense qu'on peut créer à chaque fois un dossier à côté de la page dans laquelle on veut inclure l'image. ce dossier aurrait le nom de la page sans l'extension `.md`.

Qu'en pensez-vous @club-1/members ?

**Comment by vincent-peugnet** [comment]
haha, ok, on étaient trop sérieux en fait, on faisait le taff de sphinx à sa place !

**Comment by vincent-peugnet** [comment]
> Du coup il faudrait choisir une nouvelle organisation des images. Je pense qu'on peut créer à chaque fois un dossier à côté de la page dans laquelle on veut inclure l'image. ce dossier aurait le nom de la page sans l'extension `.md`.

Intéressant, l'autre solution que j'imagine serrait de renommer le dossier `_static` en `images`, comme ça il sera viré *at compile time* si j'ai bien compris ?

Sinon je suis plutôt partant pour cette idée !

**Comment by n-peugnet** [comment]
@vincent-peugnet :
> @n-peugnet :
> > Du coup il faudrait choisir une nouvelle organisation des images. Je pense qu'on peut créer à chaque fois un dossier à côté de la page dans laquelle on veut inclure l'image. ce dossier aurait le nom de la page sans l'extension `.md`.
> 
> Intéressant, l'autre solution que j'imagine serrait de renommer le dossier `_static` en `images`, comme ça il sera viré _at compile time_ si j'ai bien compris ?

C'est une possibilité, mais il y a déjà d'autres fichiers dedans, qui eux sont bien à leur place. Par exemple le CSS et le fichier text du tuto web, mais il y en a peut-être encore d'autres.
