### ISSUE TITLE
Page FAQ

### ISSUE THREAD

**Issue by n-peugnet** [club-1/docs#134]
Après discussion avec @vincent-peugnet il serait intéressant d'ajouter une page FAQ avec les questions qui nous sont souvent posées et dont on ne sais pas vraiment où mettre ces infos.

Probablement dans une page `info/faq.md`.

**Comment by vincent-peugnet** [comment]
Première idée de question :

Est ce que je peux héberger mes emails avec mon nom de domaine et créer plein d'adresses indépendantes ??

réponse courte : NON

réponse longue : il vaut mieux utiliser le registar qui sert à louer le nom de domaine qui propose souvent un service de boîte mail. C.f. Gandhi
