### ISSUE TITLE
Infos sur le séparateur + dans le nom d'utilisateur des adresses email

### ISSUE THREAD

**Issue by n-peugnet** [club-1/docs#148]
C'est un tricks intéressant.

**Comment by vincent-peugnet** [comment]
wtf ? c quoi ce tricks ????

**Comment by n-peugnet** [comment]
http://www.postfix.org/postconf.5.html#recipient_delimiter



Haaaaaa ouais non mais en plus avec le `.forward+foo` ça devient méga intéressant !

**Comment by n-peugnet** [comment]
En gros c'est un peu des alias à la volée. Et en plus tu peux toi même les rediriger ce Mme tu veux avec le `.forward+foo` et tu peux carrément renvoyer vers un fichier genre `/dev/null` pour directement tout ignorer.

**Comment by vincent-peugnet** [comment]
Waaa ça à l'air génial mais ça casse la tête haha j'arrive pas à être sûr même après avoir ou trois fois

**Comment by n-peugnet** [comment]
En fait si qqun envoie un mail à `vincent+prout@club1.fr` par défaut il va arriver dans ta boîte mail.

Déjà c'est assez intéressant pour faire potentiellement des filtres perso qui rangerait les emails dans un dossier en fonction de l'adresse de réception.

Mais en plus de ça ça donne la possibilité de faire créer des alias sur ces nouvelles adresses. Par exemple au niveau du fichier alias il est possible de rediriger `vincent+prout` différemment de `vincent`. Et encore mieux, avec `/home/Vincent/.forward+prout` un utilisateur peut choisir lui même de rediriger cette adresse différemment de son adresse principale.

**Comment by n-peugnet** [comment]
Okay bb !! Je viens de configurer [Sieve](https://github.com/club-1/hosting/issues/51) et ça marche nickel sans être trop compliqué !
