### ISSUE TITLE
La page infrastructure fait un peu doublon avec la doc

### ISSUE THREAD

**Issue by n-peugnet** [club-1/docs#75]
Je pense qu'il faudrait lister l'ensemble des informations qui sont dans cette page et pas dans la doc, puis les y déplacer, dans la section "informations générales".

https://club1.fr/infrastructure/ &rarr; https://club1.fr/docs/fr/info/general.html

**Comment by LeilaRenard** [comment]
Et complètement supprimer la page https://club1.fr/infrastructure/ après du coup ?

**Comment by n-peugnet** [comment]
> Et complètement supprimer la page https://club1.fr/infrastructure/ après du coup ?

C'est ce que j'imaginais oui.
