### ISSUE TITLE
ajouter un screenshot pour la page services/drive

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/docs#94]

**Comment by n-peugnet** [comment]
@LeilaRenard :
> Est-ce qu'il faudrait pas plutôt le mettre dans une page tuto ? Jusqu'ici les screenshot semblent plutôt être là bas, c'est plus une question de comment vous voulez organiser la doc.

Hmm disons que je ne pense pas qu'il y aurait besoin de faire un tuto pour le drive. Et puis cette page est un peu vide.
